kind: Deployment
apiVersion: apps/v1
metadata:
  name: dev-nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-nexus
  template:
    metadata:
      labels:
        app: dev-nexus
    spec:
      containers:
      - name: dev-nexus
        image: sonatype/nexus3
        ports:
        - containerPort: 8081
          name: nexus-http
        volumeMounts:
          - name: nexus-data
            mountPath: /nexus-data
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: dev-nexus-data
---
kind: Service
apiVersion: v1
metadata:
  name: dev-nexus
spec:
  type: NodePort
  selector:
    app: dev-nexus
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 28081

