kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-nexus-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
  storageClassName: "managed-nfs-storage"

