kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
# "provisioner" can be whatever you want,
# but must match deployment's env PROVISIONER_NAME
provisioner: nfs-storage
parameters:
  archiveOnDeete: "false"

