kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: # pick a name for this PVC
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: # determine the size in Mi/Gi, like so on

