kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim  # whatever you want
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi  # you have to determine the size

