kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
    - name: test-pod
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nfs-pvc
          mountPath: "/my-nfs"
          readOnly: false
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim  # exactly same as claimed

