kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rbd-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Mi

