kind: Deployment
apiVersion: apps/v1
metadata:
  name: alex-nginx
spec:
  selector:
    matchLabels:
      by: alex
  template:
    metadata:
      name: alex-nginx
      labels:
        by: alex
    spec:
      containers:
        - name: alex-nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ceph-rbd
              mountPath: /ceph
              readOnly: false
      volumes:
        - name: ceph-rbd
          persistentVolumeClaim:
            claimName: rbd-claim

