kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "rmm.fullname" . }}
  labels:
    app: {{ template "rmm.name" . }}
    chart: {{ template "rmm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  initPostgres: |
{{ tpl (.Files.Get "init/postgresql.sql") . | indent 4 -}}
{{- $dialect := .Values.serverConfig.dbServer.nosql.dialect | lower }}
{{- if eq $dialect "mongo" }}
  initMongo: |
{{ tpl (.Files.Get "init/mongo.js") . | indent 4 }}
{{- else if eq $dialect "influx" }}
  initInflux: |
{{ tpl (.Files.Get "init/influx.sql") . | indent 4 }}
{{- else if eq $dialect "hbase" }}
  initHbase: |
{{ tpl (.Files.Get "init/hbase.sql") . | indent 4 }}
{{- end }}
  serverConfig: |
{{ tpl (.Files.Get "config/server-config.xml") . | indent 4 }}


