FROM tomcat:8.5.31-jre8


WORKDIR /rmm

ARG VERSION
COPY portal-${VERSION}.war .

RUN set -eux; \
    rm -rf /usr/local/tomcat/webapps/ROOT/*; \
    cd /usr/local/tomcat/webapps/ROOT; \
    unzip /rmm/portal-${VERSION}.war



