#
# RMM image
#
image:
  ota: "ecgwc/helm-ota-worker"
  rmm: "ecgwc/helm-rmm-worker"
  portal: "ecgwc/helm-rmm-portal"
imageTag:
  ota: "1.0.28"
  rmm: "1.0.78"
  portal: "1.0.78"
#
# MongoDB administrator
#
mongo:
  username: admin
  password:
#
# InfluxDB administrator
#
influx:
  username: to-be-added
  password: to-be-added
#
# HBase administrator
#
hbase:
  username: to-be-added
  password: to-be-added
#
# PostgreSQL administrator
#
postgresql:
  username: postgres
  password: "OFL82Vf08c"
#
# Server_Config.xml
#
serverConfig:
  webServer:
    host: "localhost"
    port: 8080
  brokerServer:
    receive:
      type: "AMQP"
      host: "localhost"
      port: 5672
      account: "admin"
      password: "0Sak+T0OheCIKudeIttf+99w7b5YroPv28cPwEX4J2U="
      vhost: "/"
      tenant: "+"
      ssl: false
    send:
      type: "MQTT"
      host: "localhost"
      port: 1883
      account: "admin"
      password: "0Sak+T0OheCIKudeIttf+99w7b5YroPv28cPwEX4J2U="
      vhost: "/"
      tenant: "WISE-PaaS"
      ssl: false
  dbServer:
    sql:
      postgresql:
        host: "61.218.118.228"
        port: 5432
        database: "wisepaas"
        schema: "rmm"
        username: "rmm"
        password: "5msIhSQ5Ggq7alAAtFcPiQ=="
    nosql:
      dialect: "mongo"
      mongo:
        # NOTE:
        #   if mongo uses replicaset, not using array here.
        #   Instead, uses string with ';' as the delimiter.
        host: "host1;host2;host3"
        port: "port1;port2;port3"
        username: "wisepaas"
        password: "WYOayctZri8m3Af8f7N7hQ=="
        database: "WISE-PaaS"
        ssl: false
      influx:
        url: "http://localhost:8086"
        username: "wisepaas"
        password: "WYOayctZri8m3Af8f7N7hQ=="
        database: "WISEPaaS"
      hbase:
        url: "jdbc://localhost:12345"
        username: "wisepaas"
        password: "WYOayctZri8m3Af8f7N7hQ=="
        database: "WISEPaaS"

