kind: Service
apiVersion: v1
metadata:
  name: {{ template "rmm.fullname" . }}
  labels:
    app: {{ template "rmm.name" . }}
    chart: {{ template "rmm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    app: {{ template "rmm.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 80
