---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dev-mongo-express
spec:
  selector:
    matchLabels:
      app: dev-mongo-express
  template:
    metadata:
      labels:
        app: dev-mongo-express
    spec:
      containers:
        - name: dev-mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "dev-mongo-mongodb-replicaset-0.dev-mongo-mongodb-replicaset.default,dev-mongo-mongodb-replicaset-1.dev-mongo-mongodb-replicaset.default,dev-mongo-mongodb-replicaset-2.dev-mongo-mongodb-replicaset.default"
            - name: ME_CONFIG_OPTIONS_EDITORTHEME
              value: ambiance
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: ecgwc
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "@dvant1cH"
---
kind: Service
apiVersion: v1
metadata:
  name: dev-mongo-express
spec:
  type: NodePort
  selector:
    app: dev-mongo-express
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 8081

